name: hello from variables in github action

on:
  push:
    branches:
      - CI_branch
env:
  WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED
  RUNS_ON: ubuntu-24.04

jobs:
  job-1:
    runs-on: $RUNS_ON
    env:
      JOB_VAR: I_AM_JOB_1_SCOPED
    steps:
      - name: Inspect scopes job 1 step 1
        env:
          STEP_VAR: I_AM_STEP_SCOPED
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"
          echo "JOB_VAR:      $JOB_VAR"
          echo "STEP_VAR:     $STEP_VAR"

      - name: Inspect scopes job 1 step 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"
          echo "JOB_VAR:      $JOB_VAR"
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"

  job-2:
    runs-on: $RUNS_ON
    steps:
      - name: Inspect scopes job 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"
          echo "JOB_VAR:      ${JOB_VAR:-<UNSET>}"
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"